"""Initial migration - create analytics tables

Revision ID: 709eb519e805
Revises: 
Create Date: 2025-09-14 09:51:00.851606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '709eb519e805'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_stats',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_bookings', sa.Integer(), nullable=False),
    sa.Column('new_bookings', sa.Integer(), nullable=False),
    sa.Column('cancelled_bookings', sa.Integer(), nullable=False),
    sa.Column('confirmed_bookings', sa.Integer(), nullable=False),
    sa.Column('total_revenue', sa.Float(), nullable=False),
    sa.Column('avg_booking_value', sa.Float(), nullable=False),
    sa.Column('active_events', sa.Integer(), nullable=False),
    sa.Column('new_users', sa.Integer(), nullable=False),
    sa.Column('system_uptime', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_index(op.f('ix_daily_stats_date'), 'daily_stats', ['date'], unique=False)
    op.create_table('event_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('event_data', sa.Text(), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_log_created_at'), 'event_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_event_log_event_id'), 'event_log', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_log_event_type'), 'event_log', ['event_type'], unique=False)
    op.create_index(op.f('ix_event_log_id'), 'event_log', ['id'], unique=False)
    op.create_index(op.f('ix_event_log_processed'), 'event_log', ['processed'], unique=False)
    op.create_table('event_stats',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('event_name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('total_capacity', sa.Integer(), nullable=False),
    sa.Column('total_bookings', sa.Integer(), nullable=False),
    sa.Column('confirmed_bookings', sa.Integer(), nullable=False),
    sa.Column('cancelled_bookings', sa.Integer(), nullable=False),
    sa.Column('capacity_utilization', sa.Float(), nullable=False),
    sa.Column('total_revenue', sa.Float(), nullable=False),
    sa.Column('cancellation_rate', sa.Float(), nullable=False),
    sa.Column('avg_booking_value', sa.Float(), nullable=False),
    sa.Column('first_booking', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_booking', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_event_stats_category'), 'event_stats', ['category'], unique=False)
    op.create_index(op.f('ix_event_stats_event_id'), 'event_stats', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_stats_event_name'), 'event_stats', ['event_name'], unique=False)
    op.create_table('system_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_events', sa.Integer(), nullable=False),
    sa.Column('total_bookings', sa.Integer(), nullable=False),
    sa.Column('total_users', sa.Integer(), nullable=False),
    sa.Column('total_revenue', sa.Float(), nullable=False),
    sa.Column('recent_bookings', sa.Integer(), nullable=False),
    sa.Column('recent_revenue', sa.Float(), nullable=False),
    sa.Column('recent_events', sa.Integer(), nullable=False),
    sa.Column('avg_capacity_utilization', sa.Float(), nullable=False),
    sa.Column('avg_cancellation_rate', sa.Float(), nullable=False),
    sa.Column('system_uptime', sa.Float(), nullable=False),
    sa.Column('booking_growth_rate', sa.Float(), nullable=False),
    sa.Column('revenue_growth_rate', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('top_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('event_name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('total_bookings', sa.Integer(), nullable=False),
    sa.Column('total_revenue', sa.Float(), nullable=False),
    sa.Column('capacity_utilization', sa.Float(), nullable=False),
    sa.Column('booking_rank', sa.Integer(), nullable=True),
    sa.Column('revenue_rank', sa.Integer(), nullable=True),
    sa.Column('utilization_rank', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_top_events_booking_rank'), 'top_events', ['booking_rank'], unique=False)
    op.create_index(op.f('ix_top_events_event_id'), 'top_events', ['event_id'], unique=True)
    op.create_index(op.f('ix_top_events_id'), 'top_events', ['id'], unique=False)
    op.create_index(op.f('ix_top_events_revenue_rank'), 'top_events', ['revenue_rank'], unique=False)
    op.create_index(op.f('ix_top_events_utilization_rank'), 'top_events', ['utilization_rank'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_top_events_utilization_rank'), table_name='top_events')
    op.drop_index(op.f('ix_top_events_revenue_rank'), table_name='top_events')
    op.drop_index(op.f('ix_top_events_id'), table_name='top_events')
    op.drop_index(op.f('ix_top_events_event_id'), table_name='top_events')
    op.drop_index(op.f('ix_top_events_booking_rank'), table_name='top_events')
    op.drop_table('top_events')
    op.drop_table('system_metrics')
    op.drop_index(op.f('ix_event_stats_event_name'), table_name='event_stats')
    op.drop_index(op.f('ix_event_stats_event_id'), table_name='event_stats')
    op.drop_index(op.f('ix_event_stats_category'), table_name='event_stats')
    op.drop_table('event_stats')
    op.drop_index(op.f('ix_event_log_processed'), table_name='event_log')
    op.drop_index(op.f('ix_event_log_id'), table_name='event_log')
    op.drop_index(op.f('ix_event_log_event_type'), table_name='event_log')
    op.drop_index(op.f('ix_event_log_event_id'), table_name='event_log')
    op.drop_index(op.f('ix_event_log_created_at'), table_name='event_log')
    op.drop_table('event_log')
    op.drop_index(op.f('ix_daily_stats_date'), table_name='daily_stats')
    op.drop_table('daily_stats')
    # ### end Alembic commands ###
